server:
  port: 8082

crawler:
  request-headers:
    accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
    user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
    accept-encoding: gzip, deflate, br
    cache-control: max-age=0
    connection: keep-alive
    host: github.com